name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: tdengine/tdengine:3.3.5.0
      options: --user root
      volumes:
        - /etc/apt/sources.list:/etc/apt/sources.list
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: start taosd
        run: nohup taosd &

      - name: Install build-essential
        run: apt-get update && apt-get install -y build-essential curl

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
